### ISSUE TITLE
Admin page

### ISSUE THREAD

**Issue by davydov-vyacheslav** [wefork/wekan#13]
Hi All,
taking in account the fact that you're moving all the stuff from wekan's pull requests here (I do appreciate that!) I think that it would be nice to have some kind of admin page (maybe even per each board). 
Let me explain ... I believe that the most of pull requests weren't merged by @mquandalle because of he would like to them as pluggin ... and I agree with him about this decision. Not all pull-request features are useful for all wekan/wefork users and there should be mechanism to disable one or several features. It would be less messy on the screen for users which want some kind of base functionality and I hope it would be faster a bit for them as they are not trigger odd database requests

**Comment by xet7** [comment]
@davydov-vyacheslav 

I added this to wefork roadmap.

There is existing pull request on for admin page on original wekan/wekan project, I don't remember where. It would be helpful for somebody to find it and add link here.

I have not yet looked at status of plugin system. Anyway with or without it, there will settings option to enable or disable features in settings. Some platforms like Sandstorm turn those features off that Sandstorm platform already provides.

@mquendalle tried to do complete rewrite, and after that he has not had energy to review and accept pull requests for some months, that's why wefork exists. We are happy to merge back if he sometime comes more active.

**Comment by ghost** [comment]
I don't remember if it was that pull request https://github.com/wekan/wekan/pull/618

**Comment by xet7** [comment]
@soohwa 

Thanks, that's the one I was looking for! There was probably something else also mentioned on original Wekan Gitter chat but I did not have time to scroll back chat history. If someone could find that that then it would be very helpful.

@kramer65

Did you get my email? Please see:
https://github.com/wefork/wekan/wiki/FAQ
https://github.com/wefork/wekan

**Comment by ghost** [comment]
I found https://github.com/wekan/wekan/issues/353 and https://discuss.wekan.io/t/restrict-registration/71/3
And with the filter : https://github.com/wekan/wekan/issues?q=is%3Aissue+is%3Aopen+label%3AFeature%3AUser-accounts
And on the original chat at Mar 20 18:42 (Mahan @laupkram)

```
AccountsTemplates.configure({                                          // 11
  forbidClientAccountCreation: true,
  defaultLayout: 'userFormsLayout',                                    // 12
  defaultContentRegion: 'content',                                     // 13
  confirmPassword: false,                                              // 14
  enablePasswordChange: true,                                          // 15
  sendVerificationEmail: true,                                         // 16
  showForgotPasswordLink: true,                                        // 17
  onLogoutHook: function () {                                          // 18
    var homePage = 'home';                                             // 19
    if (FlowRouter.getRouteName() === homePage) {                      // 20
      FlowRouter.reload();                                             // 21
    } else {                                                           //
      FlowRouter.go(homePage);                                         // 23
    }                                                                  //
  }                                                                    //
});                                                                    //
                                                                       //
['signIn', /*'signUp',*/ 'resetPwd', 'forgotPwd', 'enrollAccount'].forEach(function (routeName) {
  return AccountsTemplates.configureRoute(routeName);                  //
});
```

**Comment by xet7** [comment]
@soohwa 

Thanks! I'll assign this to myself and start working on this.

**Comment by xet7** [comment]
There's

- translation updates mixed with pull request
- comments for variable naming that need to be checked and fixed

etc so this will take some time.

**Comment by ghost** [comment]
No pb, anyway it's a good news that is underway ^^

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#790
