### ISSUE TITLE
Profile ocassionally does not attach to user

### ISSUE THREAD

**Issue by mario-orlicky** [wefork/wekan#15]
There is a problem after logout/login the profile schema is not attached to the user. This unfortunately happens only sometimes, the refresh solves the problem. Open dev tools and check with Meteor.user().profile, probably the full profile shown only with 'invitedBoards' property is returned. Try to relogin, check the profile again. If property still visible then try again. It usually happens after first relogin to me, but used to happen on the third one as well..
- a tip: if cannot reproduce the problem, after login try to click a board and then relogin again.
If empty object is displayed try refresh and it's solved.

EDIT: If reproduced the issue notice that this also causes shortcuts for starred boards to dissapear, which are also stored in the profile

**Comment by dwrensha** [comment]
I am able to reproduce this problem. It seems that there is an unfortunate interaction between three things:
1. Meteor's built-in logic that subscribes a user to their own `Users` record, including the full `profile` field.
2. Wekan's ['board' publication](https://github.com/wefork/wekan/blob/1ad41072010fb59fdbace80a0aa049634074dac1/server/publications/boards.js#L61), which relies on some complicated magic from the [cottz:publish-relations package](https://github.com/Goluis/cottz-publish-relations) to [publish partial profiles](https://github.com/wefork/wekan/blob/1ad41072010fb59fdbace80a0aa049634074dac1/server/publications/boards.js#L106-L115) for all members of a board. Somehow this seems to overwrite the profile data that the client receives from (1).
3. Wekan's [usage](https://github.com/wefork/wekan/blob/1ad41072010fb59fdbace80a0aa049634074dac1/client/components/boards/boardBody.js#L17) of [SubsManager](https://github.com/kadirahq/subs-manager), which implies that subscriptions to 'board' don't get stopped when the user navigates away.

**Comment by dwrensha** [comment]
#20 works around the problem.

**Comment by dwrensha** [comment]
#21 works around the problem and seems less likely than #20 to cause other problems.
Of course, it still would be good to understand the root problem here! I suspect there is a bug in the cottz:publish-relations package.

**Comment by xet7** [comment]
Some errors on current version of pull request https://github.com/wefork/wekan/pull/20

**Comment by dwrensha** [comment]
I believe the main problem is that [this cursor](https://github.com/wefork/wekan/blob/1ad41072010fb59fdbace80a0aa049634074dac1/server/publications/boards.js#L106-L111) will call `subscription.added()` with an incomplete version of the user's profile. If that call to `added()` happens *before* Meteor's [autopublish of `user.profile`](https://github.com/meteor/meteor/blob/b1df3ed0ed2b686e96d89ee66252f447b3c3b87e/packages/accounts-base/accounts_server.js#L709-L724) happens, then it is the only piece of the profile that the client will see. #25 fixes this problem by avoiding the current user in this 'boards' publish.

**Comment by dwrensha** [comment]
Fixed by #25.
