### ISSUE TITLE
comments do not display until mouse over new comments field

### ISSUE THREAD

**Issue by rohku** [wefork/wekan#29]
When clicking on a card, activity and comments are not displayed automatically like before.  Only when I mouse over the new comment field (Write a comment) does it show up in the expanded view.

Not game breaking, but odd and disconcerting at first.

edit: I'm using oasis.sandstorm.io

thanks!

**Comment by dwrensha** [comment]
I was just noticing this too!

**Comment by AlexanderS** [comment]
This is https://github.com/wekan/wekan/issues/656.
