### ISSUE TITLE
are releases and stable branches planned?

### ISSUE THREAD

**Issue by verymilan** [wefork/wekan#34]
Hello again,

first of all i wasn't sure if it makes sense to continue on the original wekan discussion about wefork.

I saw commit with `for release`.
Does this mean releases are planned?
And is this repository planned for production environments?
I ask it this way because it seems like there is still no notable activity on the original wekan repo.
And i would still like a master branch for stable/release and a develop branch. :)

**Comment by dwrensha** [comment]
@tchncs I guess you are referring to https://github.com/wefork/wekan/commit/aa97867b3637b681e0b6dc5ffd4ec86bbc230fbd. I've been pushing releases of the [Sandstorm package](https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h) from this repo. I agree that it would be nice to have a split between stable and development branches so that I can push bugfixes without also pushing potentially broken new features. That said, so far most of the activity on this repo has been bugfixes.

**Comment by xet7** [comment]
@tchncs 

About original Wekan, please see:
https://github.com/wefork/wekan/wiki/FAQ

Currently only devel branch https://github.com/wefork/wekan is getting latest fixes and newest features.

New features are listed with green colour on Wefork roadmap, although I have not added all newest there yet:
https://wekan.indie.host/b/t2YaGmyXgNkppcFBq/wekan-fork-roadmap

Complete list of bugfixes and new features can be seen from closed pull requests:
https://github.com/wefork/wekan/pulls?q=is%3Apr+is%3Aclosed

**Comment by verymilan** [comment]
Thanks for your answers.
Well i am still muse if i shall switch to wefork for production.
Of course splitted branches would make this decision simplier.^^

**Comment by xet7** [comment]
@tchncs 

Yes, it depends do you want:
a) Original Wekan that has not been updated in many months
b) Wefork that is under active development and has received many bugfixes and new features

I'm not aware of any other wekan forks in active development.

**Comment by verymilan** [comment]
@xet7 your points are actually the reason why i am interested in using it. 🚀 
Looks like my current option is to trust the quality of the contributions (and i have confidence in this).

**Comment by ocdtrekkie** [comment]
My hope is that after getting some of the long-backlogged features merged into this repo they'll publish a "release", but I suppose this fork has yet to establish what a release means, what level of testing should occur before declaring one, etc.

While the fork was established off a thread called "Community governance of Wekan?", I don't think there's been a formal declaration of how this fork is governed yet.
