### ISSUE TITLE
Add feature: Mail server auth protocol to NTLM

### ISSUE THREAD

**Issue by xet7** [wefork/wekan#37]
@yaruson

You previously asked at Wekan Gitter:

> Is it possible to change mail server auth protocol to NTLM? Our server doesn't support plain user/password auth.

Could you look at these, are they of any help? I have not tested them yet.

1) [Configure Postfix to relay to Exchange with NTLM authentication](http://www.linuxquestions.org/questions/linux-newbie-8/configure-postfix-to-relay-to-exchange-server-with-ntlm-authentication-4175410961/#post4712832)

2) [Davmail as mail server proxy between Wekan and Exchange, I did not find NTLM support yet](http://davmail.sourceforge.net/)

**Comment by pierreozoux** [comment]
Actually, this is not really related to wekan, but more to https://atmospherejs.com/meteor/email

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#791
