### ISSUE TITLE
Add feature: LDAP login.

### ISSUE THREAD

**Issue by whittssg** [wefork/wekan#38]
Any chance we can get LDAP login added so that it is more business friendly?

Here is the previous request:

https://github.com/wekan/wekan/issues/119

Thanks,

**Comment by xet7** [comment]
@whittssg

Please add all info as described in 2) of
https://github.com/wefork/wekan/wiki/FAQ

So then when someone has time for it, those details are already available here.

**Comment by ocdtrekkie** [comment]
This isn't necessarily a solution to the issue, as I know many people would like LDAP support in Wekan itself, but as a reference for those who may be looking at this issue in the future: It is currently possible to use either LDAP or SAML login with Wekan via [Sandstorm for Work](https://sandstorm.io/news/2016-08-31-sandstorm-for-work-ready), which is open source, but is not free.

**Comment by whittssg** [comment]
@xet7 I am not quite sure how the other points in the FAQ would look. If an Admin page is being worked on maybe it could be a checkbox in there with a settings page for the LDAP server, port etc. I am not sure if the plugin system is working yet in Wekan but if it was maybe we could just create a LDAP login plugin ( i did something similar for my Internal NodeBB forum)

**Comment by xet7** [comment]
@whittssg 

Ok, I did read that previous issue myself, so there was this mention of LDAP in Meteor:
https://atmospherejs.com/typ/accounts-ldap

I did not read more carefully if somebody tried to work on this before, that's what I was asking about.

**Comment by whittssg** [comment]
Ah OK, I searched PRs etc on the original but I didn't see anything in regards to LDAP.

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#792
