### ISSUE TITLE
Label title change name [bug]

### ISSUE THREAD

**Issue by weaktyper** [wefork/wekan#41]
Can't seem to change the label title back to an empty string. I can change it to any string other than an empty string.

**Comment by xet7** [comment]
@weaktyper 

Can you include screenshot?

**Comment by weaktyper** [comment]
When I click save on the label below, it will not revert to an empty label. It keeps the last string entered such as `Advanced` in this case.

![label_empty_not_allowed](https://cloud.githubusercontent.com/assets/10898850/21081757/1bf4373c-bfc5-11e6-85c3-42e65d5bd7a7.png)

I have to enter a minimum of one letter to change it.

**Comment by xet7** [comment]
@weaktyper 

When I tested this, I did:
1) Add new label with black colour and text
2) Click black label to open Change Label
3) Select black label that has text
4) Click delete
5) I was then able to add black empty label back.

Does this work the same for you?

**Comment by weaktyper** [comment]
@xet7 
Yea, that works... didn't see delete at first... 
No need for this issue anymore really... can close issue i think.
Thanks.
