### ISSUE TITLE
Add feature: Using API to script Email to board/card, notifications on cards to email, etc

### ISSUE THREAD

**Issue by xet7** [wefork/wekan#42]
Asked by @smolar

**Comment by quimnuss** [comment]
We could bring this further by allowing parsing the e-mail so it goes to a specific board/card/comment.

I'm testing different options before commiting to one project and I'm am greatly interested on having this feature. I'd try to implement it myself if necessary, but I just found wekan a couple days ago so I'm yet not so familiar with the code :)

Alternatively, how could a script on the server add a card/comment ? That would superseed the whole issue as the e-mail parser could be independent of wekan, which in turn is probably related to feature request #43 

This request was also present on the wekan issue tracker: https://github.com/wekan/wekan/issues/339

**Comment by xet7** [comment]
@quimnuss 

I do recommend that you clone Wefork repo, don't add Meteor and Node.js modules. Then start reading code, it's quite logically divided to subfolders. I recommend you try implementing API #43 and Email #42 , and please ask any questions you might have about design, code etc. Wefork team is currently still small so additional contributors would speed things up. I have not yet had time to add more developer documentation, but some starting points are https://github.com/wefork/wekan/wiki/FAQ and https://github.com/wefork/wekan/wiki/Install-from-source .

There are some previous discussions about API in original https://wekan.io forums and GitHub issues.

Wefork has some SMTP settings probably for forgot password functionality, but I have not tested it. There is no IMAP settings I think.

This email issue is mostly about:
- using some IMAP server to receive mail, and then using script to read that new mail and Wefork API to add content somewhere
- When something happens Wefork, have it send Email using SMTP.

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#794
