### ISSUE TITLE
Add feature: API

### ISSUE THREAD

**Issue by xet7** [wefork/wekan#43]
Asked on original Wekan Gitter by @RaviRokkam_twitter 

RaviRokkam wanted to integrate website with Wekan, so if task is added to website, it should be added as a card to Wekan.

This would require API to access Wekan data.

For those interested in this, please add all existing previous info as listed in 2) of https://github.com/wefork/wekan/wiki/FAQ

**Comment by xet7** [comment]
Related Python-based project:
https://github.com/LINKIWI/wekan-api

**Comment by flowli** [comment]
LINKIWI's wekan-api works but seems to have read-only access. So adding a card is not included.

**Comment by xet7** [comment]
Discussion moved back to https://github.com/wekan/wekan/issues/166
