### ISSUE TITLE
Add feature: Email notification to user when he/she is mentioned

### ISSUE THREAD

**Issue by quimnuss** [wefork/wekan#44]
Follow-up from this old discussion:

https://discuss.wekan.io/t/notifications-and-email-notifications/72?u=quimnuss

**Comment by xet7** [comment]
@quimnuss 

Please describe how notifications should work step by step, and should they be on per-user settings and/or upcoming admin interface https://github.com/wefork/wekan/issues/13

**Comment by quimnuss** [comment]
Thx for the rename xet7, I was in a bit of a hurry when I ported the issue from wekan to wefork, apologies.

I'll develop the idea further. I've seen wefork already supports notifications, so that's a green light for me.

We could take it one step further by being able to subscribe to specific boards/cards and also enable/disable notifications about added/removed files, daily digests, mentions...

Also, when a new comment is added, it would be great to show its context, like some of the precedent comments.

**Comment by xet7** [comment]
Followups to #42
