### ISSUE TITLE
[Sandstorm] Long "Add member to card" menu causes vertical scrolling beyond the boundary of Wekan

### ISSUE THREAD

**Issue by ocdtrekkie** [wefork/wekan#55]
This one is probably for @dwrensha though I am unsure if the same behavior will occur in standalone Wekan as I don't use it. If you try to "Add member to card" on a Sandstorm instance of Wekan, and you have a lot of options, the popup box does not scroll, instead, it will actually go beyond the bottom of the Wekan screen, and scroll the entire frame beyond Wekan. You can see this in the Sandstorm Ports in Progress Wekan, shared here: https://oasis.sandstorm.io/shared/3T7_gZPyWs9BuuTNoWRSa3ZqLv6F-4-IdYUvKYmcs-y

While the version of Wekan above is not the latest version, I've confirmed on Sandstorm Alpha that when I upgrade the grain to the latest version, the same behavior exists.

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#804
