### ISSUE TITLE
[0.11.0] Lose port number on click on a card

### ISSUE THREAD

**Issue by ghost** [wefork/wekan#56]
I installed from source.
When i click on a card, there is no port number on the url eg :
The board is located at http://192.168.56.101:3000/b/ndbCwWLHtQJ4Jabdz/welcome-board
But the click on a card is http://192.168.56.101/b/ndbCwWLHtQJ4Jabdz/welcome-board/SohAQcD7HuodBd25F

**Comment by xet7** [comment]
This is duplicate of #57 , fix is the same, continue discussion there. Closing issue.
