### ISSUE TITLE
Add feature: Custom Fields

### ISSUE THREAD

**Issue by xet7** [wefork/wekan#61]
Similar to Trello feature:
http://blog.trello.com/trello-custom-fields

Existing discussion at original Wekan forum:
https://discuss.wekan.io/t/any-way-to-add-new-data-on-cards/362/2

This wish is from original Wekan Gitter user @TutloTutlo

I did not find any existing pull request for this yet from original Wekan.

Wefork already has Due Date, so this new feature Custom Fields is separate from that.

If somebody has more information about this, please add it so it's ready here when somebody starts implementing this.

This issue is related to #43 and making Wekan programmable.

**Comment by ehausen** [comment]
In Trello custom fields are kind of a hack and only available per board. I'm thinking a better logic would be to define **Card Types** - like content types! This would very handy: _Project_ card type, a _Contact_ card type (for CRM purposes), etc...

Looking at Trello... Please someone (or me later) continue

- User can define custom field types
  - Field Name
  - Field type (text, number, checkbox, date, dropdown, location? card reference? list reference? link? )
  - Is it displayed on the Card Front Badge when card not open

- If fields are set they are listed at the top of the card

- Fields should integrate with search and filters (not in trello)

**Comment by Abacaxi-Nelson** [comment]
Hi

i agree @ehausen, card types would be really interesting, letting every users to customize their card..

**Comment by ehausen** [comment]
Well I was actually thinking more along the lines of defining these at team or organization level - when there will be implemented. Probably the best would be to have permission where the admin can define which roles can do what.

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#807
