### ISSUE TITLE
Powerbox sharing fails with "no grains can provide the requested interface"

### ISSUE THREAD

**Issue by abliss** [wefork/wekan#79]
When I (as an admin) use the + button inside wekan to add other sandstorm members, it works pretty well. But when another user (who is not an admin) tried it with her own board, she got this:

![capture](https://cloud.githubusercontent.com/assets/215283/22111773/8e92937e-de2e-11e6-86e1-a1155d73d31d.JPG)

Typing in the dropdown does nothing. Regular sharing through the sandstorm shell seems to work though.

(This is a Sandtorm For Work install with SAML accounts.)

**Comment by dwrensha** [comment]
This is a Sandstorm issue that's not specific to Wekan. Closing in favor of https://github.com/sandstorm-io/sandstorm/issues/2827.
