### ISSUE TITLE
`xss` package not installed

### ISSUE THREAD

**Issue by jLouzado** [wefork/wekan#84]
Even while building on the `devel` branch for the first time, I'm getting an error as follows.

```
Unable to resolve some modules:

  "xss" in /home/joel/projects/wekan/client/components/main/editor.js (web.browser)
                                              
If you notice problems related to these missing modules, consider running:
                                              
  meteor npm install --save xss 
```

It's easily fixable by running the command, but is there any reason it's not been installed yet? Just asking before creating a pull request to fix it.

**Comment by stephenmoloney** [comment]
This is included in the docker file installation 
See https://github.com/wefork/wekan/blob/devel/Dockerfile#L73

**Comment by jLouzado** [comment]
@stephenmoloney okay, that makes sense but it raises a related question and I apologize if it's too basic.

When installing Wekan locally for development is it not enough to clone the repo and run `meteor` as suggested in the [documentation](https://github.com/wekan/wekan/blob/master/Contributing.md#installation)?

**Comment by xet7** [comment]
@jLouzado 

No, that does not work. Use these instructions to install Wefork from source:
https://github.com/wefork/wekan/wiki/Install-from-source

Those do work for me.

If you are unsuccessful, use VirtualBox appliance:
https://wekan.xet7.org

**Comment by jLouzado** [comment]
Oh okay... most of the basic visual features are working but I think that might be what's complicating my dev process. Thank you @xet7  and @stephenmoloney :)
