### ISSUE TITLE
Suggestions to reduce size of the meteor bundle 

### ISSUE THREAD

**Issue by stephenmoloney** [wefork/wekan#85]
### Issue:

The meteor bundle is ~80MB.

- Has anyone some suggestions on how to reduce the size of the bundle? 

- Is everything in there needed?

**Comment by stephenmoloney** [comment]
I've managed to make a wekan-alpine build in the [wekan-launchpad](https://github.com/stephenmoloney/wekan-launchpad).

The size is 115MB and ~80MB of this is the meteor bundle. Would be nice if it was possible to shrink that further.

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#822
