### ISSUE TITLE
Add feature: WIP limits

### ISSUE THREAD

**Issue by denisz1** [wefork/wekan#86]
Doing Kanban without WIP limits isn't easy. Please add WIP limits, it's really essential.

This app is really good, but would be more even more professional/useful with WIP limits.

**Comment by xet7** [comment]
@denisz1 

Please describe step by step how it would work and what is should look like.

Or link to webpage with complete description.

**Comment by denisz1** [comment]
@xet7 "WIP limits" are central part of LEAN process - a team doing LEAN (or Kanban etc.) needs them. Otherwise kanban board is just a pretty thing without real management power.

Very good info is [many explanation videos on YouTube](http://www.youtube.com/results?search_query=kanban+OR+lean+wip+limits).
[This one is very good](http://youtu.be/hLuSAuVIpI8?t=1692), I linked to the exact time 28:12 in the video.
[Short one](https://www.youtube.com/watch?v=W92wG-HW8gg)

There are plenty of explanations. Just search "kanban wip limits", and maybe:
[JIRA has it](https://www.atlassian.com/agile/wip-limits)
[More](http://www.personalkanban.com/pk/primers/the-basics-of-limiting-wip-why-limit-wip-series-post-1/#sthash.Bbe2MjeY.SkPfwsXC.dpbs)
[More](https://kanbanize.com/blog/kanban-101-applying-wip-limits/)

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/783

**Comment by denisz1** [comment]
@xet7 Are we moving back to the main project? I thought it was "dead".

**Comment by xet7** [comment]
@denisz1 Yes we are moving. I'm maintainer of Wekan now, see readme at https://github.com/wekan/wekan

**Comment by denisz1** [comment]
@xet7 Congrats Lauri... You work hard to keep it alive! Also is better name "Wekan" to "Wefork"! One sounds like Kanban and other sounds like lunch.

Maybe in some point in near future we even have WIP limits, I hope. 😄
