### ISSUE TITLE
Download file(unicode filename) action cause server process crashed with exception.

### ISSUE THREAD

**Issue by yatusiter** [wefork/wekan#87]
When click download from card with unicode(Chinese) filename (upload is OK), the server process crash with following exception : 

> ./wekan/bundle/programs/server/node_modules/fibers/future.js:280
> throw(ex);
> ^
> TypeError: The header content contains invalid characters
> at ServerResponse.OutgoingMessage.setHeader (http.js:733:13)
> at ServerResponse.res.setHeader (/home/sjyb/install/wekan/bundle/programs/server/npm/node_modules/meteor/webapp/node_modules/connect/lib/patch.js:134:22)
> at packages/cfs_http-methods/http.methods.server.api.js:599:1
> at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
> at packages/cfs_http-methods/http.methods.server.api.js:595:1
> 

----
After googled around, it's seems the HTTP header "Content-Disposition" cannot accept unicode encoding characters, and should be binary or URI encoded.

[https://en.wikipedia.org/wiki/List_of_HTTP_header_fields](url)
[https://my.oschina.net/jsan/blog/180333](url)

Temporary fix with this solution:
#bundle/programs/server/packages/cfs_access-point.js add after line 444, FS.HTTP.Handlers.Get function：
```
const originalHandler = FS.HTTP.Handlers.Get;
FS.HTTP.Handlers.Get = function (ref) {
//console.log(ref.filename);
  try {
     var userAgent = (this.requestHeaders['user-agent']||'').toLowerCase();

        if(userAgent.indexOf('msie') >= 0 || userAgent.indexOf('chrome') >= 0) {
            ref.filename =  encodeURIComponent(ref.filename);
        } else if(userAgent.indexOf('firefox') >= 0) {
            ref.filename = new Buffer(ref.filename).toString('binary');
        } else {
            /* safari*/
            ref.filename = new Buffer(ref.filename).toString('binary');
        }   
   } catch (ex){
        ref.filename = 'tempfix';
   } 
   return originalHandler.call(this, ref);
};

```

**Comment by ghost** [comment]
@yatusiter i tried your temporary fix but i cant edit the package, can you be more specific where did you add the code? (i mean after which function)

**Comment by yatusiter** [comment]
@Daniel231 just after the original definiton of FS.HTTP.Handlers.Get   

bundle/programs/server/packages/cfs_access-point.js add after line 444, FS.HTTP.Handlers.Get function：

**Comment by ghost** [comment]
@yatusiter Success! thx :D

**Comment by xet7** [comment]
Moved to https://github.com/wekan/wekan/issues/784
