### ISSUE TITLE
Question: back end other than Mongo?

### ISSUE THREAD

**Issue by romu70** [wefork/wekan#9]
Hi,
Is there any simple way to setup WeKan with another back end than Mongo? Is this on the roadmap?

Thanks.

**Comment by xet7** [comment]
@romu70 

Could you do some Google searching for projects that make interface like Mongo but translate it to another database backend like PostgreSQL or MySQL ? And also find examples how Meteor / Mongo projects have added support for other databases?

**Comment by xet7** [comment]
@romu70 

Somebody else did ask about this before, so I added it to roadmap. I have not had time to add all feature requests from original wekan project to roadmap yet.

**Comment by romu70** [comment]
Thanks a lot, so I think you deserve a little explanation ;-)

Self hosting is great but raises some issues, even more if you plan to do self-hosting with Docker:
- the more is the list of apps you want to host, the more is the list of required data back ends, and this makes self hosting more and more difficult, and resources consuming, both human and hardware
- when you self-host an application through Docker, you absolutely need to externalize the data if you want to be able to update the Docker without loosing things.

Personally, I don't need specifically a SQL DB, Redis would be great also, and maybe easier for switching from a NoSQL DB, but I don't know well both.

Thanks a lot.

**Comment by pierreozoux** [comment]
Meteor is using Mongo.
Wekan uses Meteor as a Framework.
As long as Meteor doesn't allow other db, wekan can't use any other db.

Closing this for now.

Feel free to reopen once meteor add support to other db.

**Comment by xet7** [comment]
@pierreozoux 

There can be some way to use Meteor with other databases, I did see some search results about that, it's not impossible. This is looking for somebody needing other database support to do the research.

Reopening issue.

**Comment by aegrey** [comment]
Meteor said last year it was a high priority, but with MongoDB's growing popularity I would assume it's become less so.   
   
There's a library that does it (numtel:mysql - haven't used it in a while). Hasn't been updated since mid-2016, but his example project is active (https://github.com/numtel/meteor-mysql-leaderboard). For those interested, you could try integration in your fork (I am just delving into Wekan's code, so couldn't say how heavy of a lift it'd be).

**Comment by xet7** [comment]
This issue was moved to wekan/wekan#787
