### ISSUE TITLE
Should this fork be promoted more aggressively?

### ISSUE THREAD

**Issue by ghost** [wefork/wekan#93]
There are still folk posting issues in the original repository: https://github.com/wekan/wekan/issues. I recon that instead of posting their issues on wekan/wekan they would be better off switching to wefork/wekan.

Problem is, this fork is really easy to miss. It certainly does not help that the [network page](https://github.com/wefork/wekan/network) refuses to show any useful information whatsover. "Too many forks to display" does not help anybody.

I discovered this fork merely by accident when I was trying to get Wekan running in a Docker container. I was a bit frustrated when I learned that some of the problems that I tried to solve myself had already been fixed in a different fork.

My question is: Should we somehow promote this fork more aggresively, so that more folk switch from wekan/wekan to wefork/wekan?

**Comment by xet7** [comment]
@centigrade-thomas-becker 

No need to promote.

I will merge Wefork back to Wekan in near future. I got access to original Wekan 2 days ago.

**Comment by ghost** [comment]
Good to hear!
