### ISSUE TITLE
support for anonymous edits

### ISSUE THREAD

**Issue by klischka** [wefork/wekan#94]
I use Wekan on Sandstorm and ran into one problem: I wanted a board to be editable by anyone whom I shared the link with (a barcamp). Sandstorm supports this function, but Wekan currently requires users to be logged in in order to edit. People who visit my share link need to log in. I think support for anonymous edits would benefit some users.

**Comment by dwrensha** [comment]
Previous discussion: https://github.com/wekan/wekan/issues/349

**Comment by ocdtrekkie** [comment]
Since Wefork is merging back into Wekan, this can probably be safely closed in favor of the aforementioned wekan#349
