### ISSUE TITLE
Labels drag and drop?

### ISSUE THREAD

**Issue by ovizii** [wefork/wekan#96]
I'm not 100% sure but I am pretty sure before the latest update to Wekan for Sandstorm I could drag and drop labels onto cards. I am currently using: 0.16.0~2017-03-21 from https://apps.sandstorm.io/app/m86q05rdvj14yvn78ghaxynqz7u2svw6rnttptxx49g1785cdv1h

Can someone confirm this?

**Comment by xet7** [comment]
@ovizii 

Drag and drop of labels to cards works for me on Chrome on Linux, using Sandstorm Wekan 0.16.

What browser are you using?

**Comment by ovizii** [comment]
oh, damn. really sorry about this it seems somehow my sandstorm grain lost connection and was basically offline. closing the grain and re-opening fixed things :-(
