### ISSUE TITLE
Wekan at Sandstorm is heavily outdated!

### ISSUE THREAD

**Issue by chris-kwng** [wefork/wekan#98]
At Sandstorm the Wekan app is available in version 0.16,
but Wekan has reached version 0.32 in the meantime.

No update since more than 4 month! Please fix that!

**Comment by ocdtrekkie** [comment]
Issues only need to be filed on the official wekan/wekan repository at this point.

**Comment by chris-kwng** [comment]
I did not know the right place for the issue. THX.

For latecomers: https://github.com/wekan/wekan/issues/1166
